(defproject rendezvous "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.4.0"]
                 [org.slf4j/slf4j-api "1.6.6"]
                 [org.slf4j/slf4j-log4j12 "1.6.6"]
                 [org.clojure/tools.logging "0.2.3"]
                 [org.clojure/tools.cli "0.2.1"]
                 [aleph "0.3.0-beta6"]
                 [camel-snake-kebab "0.1.0-SNAPSHOT"]
                 [ring "1.1.1"]
                 [compojure "1.1.1"]
                 [ring-json-params "0.1.3"]
                 [hiccup "1.0.0"]]
  :dev-dependencies [[lein-marginalia "0.8.0-SNAPSHOT"]
                     [criterium "0.2.1"]]
  :main rendezvous.core)
